### ISSUE TITLE
qual é a licença deste repositório?

### ISSUE THREAD

**Issue by ghost** [PauloGoncalvesBH/treinamento-git#27]
Oi.

Gostaria de saber qual é a licença deste repositório. Qual é a licença deste repositório? é o MIT? GPL? Unlicensed? (Gostaria de usar o repositório para algo que estou fazendo, criando)

**Comment by PauloGoncalvesBH** [comment]
oi @villenmarx, é MIT

**Comment by ghost** [comment]
Oi PauloGoncalvesBH.

> oi @villenmarx, é MIT

Sei que há vários tipos de licenças proprietárias, abertas, livres. Sobre a licença MIT, acho bem legal a ideia da permissividade que ela propõe. E valeu pela informação. ps: amo ilustração, e tó pensando em ilustrar o treinamento git.
