### ISSUE TITLE
outros formatos de mídia

### ISSUE THREAD

**Issue by ghost** [PauloGoncalvesBH/treinamento-git#33]

**Comment by PauloGoncalvesBH** [comment]
Olá @lucasnuic, não pensei em fazer essa alteração no treinamento. Gosto de manter no Github pois outras pessoas podem colaborar e exige pouco esforço de manutenção.

O que tem em mente?

**Comment by PauloGoncalvesBH** [comment]
Concordo contigo @lucasnuic, uma etapa futura pode ser publicar gratuitamente no leanpub usando o github actions.
O que precisar de minha ajuda, cá estou.

**Comment by PauloGoncalvesBH** [comment]
o repositório está indisponível @lucasnuic

**Comment by rafaelribon** [comment]
@lucasnuic  aqui funcionou
